language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: r7KcxNPSsHFGnBbXWH8TUoEmKxeMPJAm3VEDMtA3XgVJ5t/cIVCFOBIiX5nz/2tmtXaCm//rSX3QZeq+lyhEWDdknEGaViW0o2VnKpMdtF6hEYUcm6QXCIMvnWNbAON2M7TdeCqagUR3hrDTMxuztD7GvyI7z0DQQr3qZ2MqTfzFVleWlzS+pjJS0KZi4fKnEXBq6YTSViKPOmU3QhSsiTWSKGzxkS30fBVGjP4VJ7YN6nRwg8jRppEIbSWYY5jGc+gikdGdjlNSKq677kw0beSmD4acBruJmLsR70gRuJeMou6wIH7b5qAkv6xzdG3Egp+iVm77dCwLL7RNypYALv/XmKrPSslHYzOFCfzi3Oz5ePGjGtnkJa1aGXAiw5r9EEiSvb/oqdRaHpYKEnBIxqIKabqHRuGANmneMIPvy2hRA3XMYpD/KVIcCzEbnRV1A/OBLvkQ5wN86M5sH60XPvKZJGqshAH4HiWhHoIs1ojQlfVsLNHNW+Kbt9qaAHJdsTF3GJ0JPThRAZsPt72gqjgqo2SAIU/EsKWFu/7I/4dOQxbLhWzsvpby7WgmLIPx4DeNz2lPTSYpm9aSe4PA2EZA941upr2qFXxA+Cg53zICDwRMhTx6dNs6Ld1tiUvcK/hppJJLyJ3F1LJrCrgEhnNmOHT3AHL2kh8HyDTZKbA=
  app: serene-fortress-23837
  on:
    repo: CraigPounds/react-trello-testing
